server:
  port: 8882
  shutdown: graceful
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: practice_route
          uri: lb://hl-cloud-service-practice
          predicates:
            - Path=/hl-practice/**
          filters:
            - RewritePath=/hl-practice/(?<path>.*), /$\{path}
        - id: practice_route2
          uri: lb://hl-cloud-service-practice
          predicates:
            - Path=/practice/**
          filters:
            - RewritePath=/practice/(?<path>.*), /$\{path}
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ '*' ]
  endpoint:
    health:
      show-details: always